car_app/urls.py
from django.conf.urls import url
from car_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'car_app'

urlpatterns = [
	url(r'^new/model/$', views.model_new, name='model_new'),
	url(r'^model/(?P<pk>[0-9]+)/edit/$', views.model_edit, name='model_edit'),	
	url(r'^models/$', views.models, name='models'),
	url(r'^models/(?P<pk>[0-9]+)/$', views.model_detail, name='model_detail'),

	url(r'^new/number/$', views.number_new, name='number_new'),
	url(r'^number/(?P<pk>[0-9]+)/edit/$', views.number_edit, name='number_edit'),	
	url(r'^numbers/$', views.numbers, name='numbers'),
	url(r'^numbers/(?P<pk>[0-9]+)/$', views.number_detail, name='number_detail'),

	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),	
	url(r'^posts/$', views.posts, name='posts'),
	url(r'^post/(?P<pk>[0-9]+)/$',  views.post_detail, name='post_detail'), 

]

car_trucks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from car_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^truck/', include('car_app.urls')), 
    url(r'^$', views.index, name='index'), 
]

car_app/models.py
from django.db import models
from django.utils import timezone


class TruckModel(models.Model):
	model_name = models.CharField(max_length=20, unique=True)
	max_capacity = models.IntegerField(default=0)
	model_description = models.TextField(max_length=1000, 
			help_text='Enter a brief description of the Truck Model', blank=True, null=True)
			
	class Meta:
		verbose_name = 'TruckModel'
		verbose_name_plural = 'TruckModels'
		
		
	def __str__(self):
		return self.model_name


class TruckNumber(models.Model):
	bort_number = models.CharField(max_length=20, unique=True)
	model_name = models.ForeignKey(TruckModel, on_delete=models.SET_NULL, null=True)
	truck_number_description = models.TextField(max_length=1000, 
			help_text='Enter a brief description of the Truck Number', blank=True, null=True)
	
	current_weight = models.IntegerField(default=0)
		
	registration_date = models.DateTimeField(
			default=timezone.now)
	current_work_start_date = models.DateTimeField(
			blank=True, null=True)
	overload = models.FloatField(default=0)
	
	class Meta:
		verbose_name = 'TruckNumber'
		verbose_name_plural = 'TruckNumbers'
		
	def __str__(self):
		return str(self.bort_number)
		


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
        
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title
        
        
        

car_app/forms.py
from django import forms
from car_app.models import TruckModel, TruckNumber, Post


class TruckModelForm(forms.ModelForm):
    class Meta:
        model =  TruckModel
        fields = ('model_name', 'max_capacity', 'model_description', )


class TruckNumberForm(forms.ModelForm):
    class Meta:
        model =  TruckNumber
        fields = ('bort_number', 'model_name', 'current_weight', 'truck_number_description', )
        

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)
        
        
        
        

car_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Max, Avg, FloatField, Count, F 

from car_app.models import TruckModel, TruckNumber, Post
from car_app.forms import TruckModelForm, TruckNumberForm, PostForm


def update_overload():
    overloads = TruckNumber.objects.select_related('model_name').annotate(
	    overload_100_1 = (F('current_weight') - F('model_name_id__max_capacity')) * 100 / F('model_name_id__max_capacity'), 
	    ).values()
    for item in overloads:     
        truck_instance = get_object_or_404(TruckNumber, pk=item['id'])
        
        if truck_instance.overload == 0:
            truck_instance.overload = item['overload_100_1']
            truck_instance.save()
	
    return overloads


def index(request, truck_model_select="all"):
	try:
		all_truck_models = TruckModel.objects.all()
		all_truck_numbers = TruckNumber.objects.all()
		requested_numbers = TruckNumber.objects.all()
	except (KeyError, MultiValueDictKeyError) as key_error:
		print('key_error = ', key_error)

	if len(request.GET) == 0:
	    requested_numbers = TruckNumber.objects.all()     
	elif request.GET['truck_model_select'] == 'all':
	    requested_numbers = TruckNumber.objects.all()	    

	else:
		try:
			model_id = request.GET['truck_model_select']
			model_id_int = int(model_id)
			requested_numbers = TruckNumber.objects.filter(model_name=model_id_int)
			
		except (KeyError, UnboundLocalError)  as err:
			print('KeyError from index.html', err)
			
		except (MultiValueDictKeyError, django.utils.datastructures.MultiValueDictKeyError) as multy_error:
			requested_numbers = TruckNumber.objects.all()

	current_moment_overloads = update_overload()
	amount_numbers = len(requested_numbers)

	context = {
		'all_truck_models': all_truck_models,
		'requested_numbers': requested_numbers, 
		'amount_numbers': amount_numbers,
	}
	return render(request, 'car_app/index.html', context)



# Models

def models(request):
	all_models = TruckModel.objects.all()
	paginator = Paginator(all_models, 5) 
	page = request.GET.get('page')
	try:
	    models = paginator.page(page)
	except PageNotAnInteger:
	    models = paginator.page(1)
	except EmptyPage:
	    models = paginator.page(paginator.num_pages)
		
	context = {'models': models}	
	return render(request, 'car_app/models.html', context)


def model_detail(request, pk):
    model_instance = get_object_or_404(TruckModel, pk=pk)
    truck_numbers_for_this_model = model_instance.trucknumber_set.order_by('bort_number')

    context = {
        'model_instance': model_instance, 
        'truck_numbers_for_this_model': truck_numbers_for_this_model, 
        }
    return render(request, 'car_app/model_detail.html', context)


def model_new(request):
    if request.method == "POST":
        model_form = TruckModelForm(request.POST)
        if model_form.is_valid():
            model = model_form.save(commit=False)
            model.save()
            return redirect('car_app:model_detail', pk=model.pk)
    else:
        model_form = TruckModelForm()
    return render(request, 'car_app/add_model.html', {'model_form': model_form})


def model_edit(request, pk):
    model = get_object_or_404(TruckModel, pk=pk)
    if request.method == "POST":
        model_form = TruckModelForm(request.POST, instance=model)
        if model_form.is_valid():
            model = model_form.save(commit=False)
            model.save()
            return redirect('car_app:model_detail', pk=model.pk)

    else:
        model_form = TruckModelForm(instance=model)
    
    return render(request, 'car_app/add_model.html', {'model_form': model_form})  


# Numbers

def numbers(request):
	all_numbers = TruckNumber.objects.all()
	paginator = Paginator(all_numbers, 5) 
	page = request.GET.get('page')
	try:
	    numbers = paginator.page(page)
	except PageNotAnInteger:
	    numbers = paginator.page(1)
	except EmptyPage:
	    numbers = paginator.page(paginator.num_pages)
		
	context = {'models': numbers}	
	return render(request, 'car_app/numbers.html', {'numbers': numbers})


def number_detail(request, pk):
    number_instance = get_object_or_404(TruckNumber, pk=pk)

    context = {
        'number_instance': number_instance, 
        }
    return render(request, 'car_app/number_detail.html', context)   


def number_new(request):
    if request.method == "POST":
        number_form = TruckNumberForm(request.POST)
        if number_form.is_valid():
            number = number_form.save(commit=False)
            current_truck_overload = ((number.current_weight - 
                number.model_name.max_capacity) / number.model_name.max_capacity) * 100

            format_current_truck_overload = float('{0:.2f}'.format(current_truck_overload))
            number.overload = format_current_truck_overload
            number.save()
            return redirect('car_app:number_detail', pk=number.pk)
    else:
        number_form = TruckNumberForm()
    return render(request, 'car_app/add_number.html', {'number_form': number_form})


def number_edit(request, pk):
    number = get_object_or_404(TruckNumber, pk=pk)
    if request.method == "POST":
        number_form = TruckNumberForm(request.POST, instance=number)

        if number_form.is_valid():
            number = number_form.save(commit=False)
            
            current_truck_overload = ((number.current_weight - 
                number.model_name.max_capacity) / number.model_name.max_capacity) * 100
            number.overload = float('{0:.2f}'.format(current_truck_overload))

            number.save()
            return redirect('car_app:number_detail', pk=number.pk)
    else:
        number_form = TruckNumberForm(instance=number)
    
    return render(request, 'car_app/add_number.html', {'number_form': number_form}) 


# Posts
def posts(request):
	all_posts = Post.objects.order_by('-published_date')
	paginator = Paginator(all_posts, 2) 
	page = request.GET.get('page')
	try:
	    posts = paginator.page(page)
	except PageNotAnInteger:
	    posts = paginator.page(1)
	except EmptyPage:
	    posts = paginator.page(paginator.num_pages)
		
	context = {'posts': posts}	
	return render(request, 'car_app/posts.html', context)


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'car_app/post_detail.html', {'post': post})  


def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('car_app:post_detail', pk=post.pk)
	else:
		form = PostForm()

	return render(request, 'car_app/post_edit.html', {'form': form})


def post_edit(request, pk):
	print('Invoke post_edit ', pk)
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('car_app:post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)

	return render(request, 'car_app/post_edit.html', {'form': form})    

car_app/templates/car_app/add_model.html
{% extends 'car_app/base.html' %}


{% block content %}
    <h1>Новая модель</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ model_form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock content %}

car_app/templates/car_app/add_number.html
{% extends 'car_app/base.html' %}


{% block content %}
    <h1>Новая машина</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ number_form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock content %}

car_app/templates/car_app/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<html >
  <head>
    <title> {% block title %} {% endblock %} </title>
    <meta charset ="utf -8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        
	
    <!-- Bootstrap CSS -->  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap -->	
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" media="screen">

	<!-- Bootstrap Form Helpers -->
	<link rel="stylesheet" href="{%  static 'css/bootstrap-formhelpers.min.css' %}"  media="screen">
    <link rel="stylesheet" href="{%  static 'css/style.css' %}"/>

    {% block static %}
    {% endblock %}

  </head>

  <body>
  	<!--block pageWrapper - begin-->
  	<div class = "pageWrapper"  style="overflow: visible;">
  		<nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
          
            <li><a class="navbar-brand" href="{% url 'index' %}">Main</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

            <li><a class="navbar-link" href="{% url 'car_app:models' %}">Models</a></li>
            <li><a class="navbar-link" href="{% url 'car_app:numbers' %}">Numbers</a></li>
            <li><a class="navbar-link" href="{% url 'car_app:posts' %}">Posts</a></li>

            <li><a class="navbar-link" href="{% url 'car_app:model_new' %}">New model</a></li>
            <li><a class="navbar-link" href="{% url 'car_app:number_new' %}">New number</a></li>
            <li><a class="navbar-link" href="{% url 'car_app:post_new' %}">New post</a></li>
      
          </ul>
        </div>
      </nav>
  	</div>


  	<div class = "pageWrapper"  style="overflow: visible;">
    
    	<div class ="container">
        	{% block content %}                               
            {% endblock %}
            	
    	</div>
        
    </div>
    <!--block pageWrapper - end-->


  	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	
	<!-- Bootstrap -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	<!-- Bootstrap Form Helpers -->
	<script src="{% static  'js/bootstrap-formhelpers.min.js' %}"></script>
	
	
	<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	<script src="dist/js/bootstrap-select.min.js"></script>

  <footer></footer>
  </body>

</html>

car_app/templates/car_app/index.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}

{% block content %}

  <div id="post-form">
    <form id="truck-search-form"  method="get">
    	<label class="field truck-choice" for="truck-choice">Модели:</label>
    
    		<select  id="truck_model_select" class="custom-select" name="truck_model_select">
    		<!-- <option  selected="selected">Выбрать </option>  -->
    			<option value="all" > Все </option> 
    			   		
    			{% for item  in all_truck_models %} 
    		 	<option value="{{item.id}}">{{item.model_name}}</option> 
    		 	{% endfor  %}
    		 	
    		</select>    		 
    		<button id="show_model" type="submit" action="" name="" button_value= item_id_value >Применить</button>
    		    
    </form>
    
    Всего машин: {{amount_numbers}}
  </div>


<h1>Машины парка: </h1>
  <!--  TABLE    -->
			
  {% if requested_numbers %}
	  <table class="table table-hover">
	    <thead>		
	      <th>Бортовой номер</th>
	      <th>Модель</th>
	      <th>Макс. грузоподъемность,т</th>
	      <th>Текущий вес,т</th>
	      <th>Перегруз,%</th>  
	    </thead>

	    <tbody id="truck-table">	
	      {% for truck in requested_numbers  %}
	        <tr>		
	          <td><a href="{% url 'car_app:number_detail' pk=truck.pk %}">{{truck.bort_number}} </a></td>
	          <td>{{truck.model_name}}</td>
	          <td>{{truck.model_name.max_capacity}}</td>
	          <td>{{truck.current_weight}}</td>
	          <td>{{truck.overload}} </td>
	        </tr>
	        {% endfor  %}	 
		</tbody>	
  	  </table>

    {% else %}
      <p>No entries</p>
    {% endif  %}

{% endblock  %}

car_app/templates/car_app/model_detail.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}

{% block content %}

  <a class="btn btn-default" href="{% url 'car_app:model_edit' pk=model_instance.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
  <h1>Описание модели</h1>

  <h4>Модель: {{model_instance.model_name}}</h4>
  <p></p>
  <p>Максимальная грузоподъемность: {{model_instance.max_capacity}}</p>
  <p>Описание: {{model_instance.model_description}}</p>

  
{% endblock  %}

car_app/templates/car_app/models.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}


{% block content %}


  <h2>Все модели парка</h2>
  </br>

  {% for model in models %}
    <h2><a href="{% url 'car_app:model_detail' pk=model.pk  %}">{{model.model_name}}</a></h2>

    <h4>Максимальная грузоподъемность: {{model.max_capacity}} тонн</h4> 
    <h4>Описание модели: </h4> 
    <p>{{model.model_description}}</p>
    </br>
  {% endfor  %}

  <div class="pagination">
    <span class="step-links">
      {% if models.has_previous %}
        <a href="?page={{ models.previous_page_number }}">prev</a>
      {% endif %} 
      
      <span class="current">
        Page {{ models.number }} of {{ models.paginator.num_pages }}.
      </span>
      
      {% if models.has_next %}
        <a href="?page={{ models.next_page_number }}">next</a>
      {% endif %}
    </span>    
  </div>

{% endblock content %}

car_app/templates/car_app/number_detail.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}
{% block content %}

<a class="btn btn-default" href="{% url 'car_app:number_edit' pk=number_instance.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>


<h2>Описание машины </h2>

  <h4>Модель: {{number_instance.model_name}}</h4>
  <p></p>
  <h4>Бортовой номер: <a href="{% url 'car_app:number_detail' pk=number_instance.pk %}">{{number_instance.bort_number}}</a></h4>
  <p>Текущая загруженность машины: {{number_instance.current_weight}} тонн</p>
  <p>Перегруз машины: {{number_instance.overload}} %</p>
  <p>Описание: {{number_instance.truck_number_description}}</p>

{% endblock  %}

car_app/templates/car_app/numbers.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}

{% block content %}
  <h2>Cписок машин в парке</h2>
  
    {% for number in numbers %}
      <h3>Бортовой номер машины: <a href="{% url 'car_app:number_detail' pk=number.pk %}">{{number.bort_number}}</a></h3>		
      <p>Текущая загруженность: {{number.current_weight}} тонн</p>
      <p>Перегруз: {{number.overload}} %</p>
      </br>
    {% endfor  %}

      <div class="pagination">
        <span class="step-links">
          {% if numbers.has_previous %}
            <a href="?page={{ numbers.previous_page_number }}">prev</a>
          {% endif %}
  
        <span class="current">
          Page {{ numbers.number }} of {{ numbers.paginator.num_pages }}.
        </span>
      
        {% if numbers.has_next %}
          <a href="?page={{ numbers.next_page_number }}">next</a>
        {% endif %}        
        </span>   
      </div>

{% endblock  %}

car_app/templates/car_app/post_detail.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}
{% block content %}


	<a class="btn btn-default" href="{% url 'car_app:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
  
	<h4>Post detail:</h4>
  	</br>
  	<div class="post">
  		{% if post.published_date %}
  			<div class="date">
  				{{post.published_date}}
  			</div>
  		{% endif %}
  		
  		<h1>{{post.title}}</h1>
  		<p>{{post.text}}</p>

  	</div>


{% endblock  %}

car_app/templates/car_app/post_edit.html
{% extends 'car_app/base.html' %}


{% block content %}
    <h1>Новая статья</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

car_app/templates/car_app/posts.html
{% extends 'car_app/base.html' %}
{% load staticfiles %}


{% block content %}
  
  {% for post in posts %}
    {% if post.published_date %}
      <div class="date">
        {{post.published_date}}
      </div>
          
      <h4><a href="{% url 'car_app:post_detail' pk=post.pk %}">{{post.title}}</a></h4>
      <p>{{ post.text|linebreaksbr }}</p>
      </br></br>
     
    {% endif %}    
  {% endfor %}
  
  
  <div class="pagination">
    <span class="step-links">
      {% if posts.has_previous %}
        <a href="?page={{ posts.previous_page_number }}">prev</a>
      {% endif %}
      
      <span class="current">
        Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
      </span>
      
      {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">next</a>
      {% endif %}
    </span>   
  </div>


{% endblock  %}